"""create core NETRIXA tables

Revision ID: 4e7440c60a9e
Revises: e67ac2ef95c1
Create Date: 2026-09-04 22:50:41.066509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # always imported: needed whenever a migration touches a Geometry column
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e7440c60a9e'
down_revision: Union[str, None] = 'e67ac2ef95c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('facility_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('facility_type', sa.String(), nullable=False),
    sa.Column('facility_category', sa.Enum('refinery', 'petrochemical', 'thermal_power', 'steel', 'mining', 'lng', 'other', name='facility_category'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('facility_id')
    )
    op.create_index('ix_facilities_geom', 'facilities', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_facilities_state', 'facilities', ['state'], unique=False)
    op.create_table('thermal_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('detection_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('brightness_temperature', sa.Float(), nullable=False),
    sa.Column('frp', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('satellite', sa.String(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('land_cover', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_thermal_events_detection_time', 'thermal_events', ['detection_time'], unique=False)
    op.create_index('ix_thermal_events_geom', 'thermal_events', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_thermal_events_state', 'thermal_events', ['state'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alert_severity'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='alert_status'), nullable=False),
    sa.Column('recommended_action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['thermal_events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('analyst_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('decision', sa.Enum('CONFIRMED', 'FALSE_POSITIVE', 'NEEDS_REVIEW', name='feedback_decision'), nullable=False),
    sa.Column('analyst_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['thermal_events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('classification', sa.Enum('Potential Industrial Fire', 'Industrial Fire', 'Persistent Industrial Thermal Source', 'Gas Flare', 'Agricultural Burning', 'Wildfire', 'Mining Activity', 'Unknown / Insufficient Evidence', name='classification_type'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('probability_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('persistence_score', sa.Float(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('historical_deviation', sa.Float(), nullable=False),
    sa.Column('industrial_proximity', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'NONE', name='proximity_level'), nullable=False),
    sa.Column('spatial_change_score', sa.Float(), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_action', sa.String(), nullable=False),
    sa.Column('persistence', sa.Enum('NORMAL_PERSISTENT', 'ABNORMAL_PERSISTENT', 'SUDDEN_EVENT', 'INTERMITTENT', 'UNKNOWN', name='persistence_type'), nullable=False),
    sa.Column('spatial_change', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'STABLE', name='spatial_change_level'), nullable=False),
    sa.Column('historical_mean', sa.Float(), nullable=True),
    sa.Column('historical_std', sa.Float(), nullable=True),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('observations', sa.Integer(), nullable=False),
    sa.Column('first_observed', sa.Date(), nullable=True),
    sa.Column('last_observed', sa.Date(), nullable=True),
    sa.Column('facility_name', sa.String(), nullable=True),
    sa.Column('facility_distance', sa.Float(), nullable=True),
    sa.Column('facility_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['thermal_events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_event_analysis_event_id')
    )
    op.create_table('historical_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('obs_date', sa.Date(), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('frp', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['thermal_events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'obs_date', name='uq_historical_obs_event_date')
    )
    op.create_index('ix_historical_obs_event_id', 'historical_observations', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_historical_obs_event_id', table_name='historical_observations')
    op.drop_table('historical_observations')
    op.drop_table('event_analysis')
    op.drop_table('analyst_feedback')
    op.drop_table('alerts')
    op.drop_index('ix_thermal_events_state', table_name='thermal_events')
    op.drop_index('ix_thermal_events_geom', table_name='thermal_events', postgresql_using='gist')
    op.drop_index('ix_thermal_events_detection_time', table_name='thermal_events')
    op.drop_table('thermal_events')
    op.drop_index('ix_facilities_state', table_name='facilities')
    op.drop_index('ix_facilities_geom', table_name='facilities', postgresql_using='gist')
    op.drop_table('facilities')
    # ### end Alembic commands ###
